### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by akdasa** [akdasa-studios/lectorium#12]
## Problem Statement:
A track can be available in multiple languages: the original speaker's language, a translator's language, and translated transcripts in various languages. Users should be able to find a track in any language it is presented.

## Proposed Solution:
Extend the TrackInfo model to incorporate all information about available languages.

## Implementation Plan:
Update the `languages` field of the `TrackInfo model`. It should contain an array of the following objects:

```json5
{ 
    language: string,
    source: 'track'       // lecture was given or translated into this language
          | 'transcript', // app has transcript on that language
    type: 'original'     // it is original audio
        | 'generated'    // machine-generated
        | 'redacted'     // machine-generated but redacted by human
}
```

For example, the lecture was given in English and translated into Russian by a translator, and we have transcriptions for Russian and Serbian (automatically translated) it will look like this:

```json5
[
  // Lector speaks in English
  { language: 'en', source: 'track', type: 'original' }, 
  
  // Translator translated into his native Russian 
  { language: 'ru', source: 'track', type: 'original' }, 
  
  // Transcript was generated but redacted
  { language: 'ru', source: 'transcript', type: 'redacted' }  
  
  // Transcript was generated, but not redacted
  { language: 'sr', source: 'transcript', type: 'generated' } 
]
```

So users can find that lecture in Serbian, and we can inform them that only automatically translated transcription is available for that track.

## Implementation Plan:
- [x] https://github.com/akdasa-studios/lectorium-tools/issues/1
- [x] https://github.com/akdasa-studios/lectorium-mobile/issues/17
- [x] https://github.com/akdasa-studios/lectorium/issues/12

**Comment by akdasa** [comment]
Done
